DELETE FROM [dbo].[File]
DELETE FROM [dbo].[Folder]
DELETE FROM [dbo].[Tag]
DELETE FROM [dbo].[ISO]

DBCC CHECKIDENT ([File], RESEED, 0)
DBCC CHECKIDENT ([Folder], RESEED, 0)
DBCC CHECKIDENT ([ISO], RESEED, 0)
DBCC CHECKIDENT ([Tag], RESEED, 0)